title: CSP.guru
author: Energy Transitions and Public Policy, RIFS Potsdam
email: richard.thonig@rifs-potsdam.de
description: >-
  This site provides the CSP.guru dataset of concentrating solar power plants.
url: "https://csp.guru/"
github_username:  repolicy

data_dir: csp-guru
markdown: kramdown
theme: minima
header_pages:
    - data.md
    - explore.md
    - metadata.md
    - paper.md
    - about.md
